services:
  - type: web
    name: uni-config-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      # Enable ChromeDriver logging
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE 
        value: "1"
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    autoDeploy: true 